/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#c8c6c5",
        "outline-variant": "#444748",
        "surface": "#121314",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#3d0000",
        "surface-bright": "#393939",
        "error": "#ffb4ab",
        "surface-tint": "#c8c6c5",
        "outline": "#8e9192",
        "primary-fixed-dim": "#c8c6c5",
        "on-surface-variant": "#c4c7c7",
        "secondary-container": "#474746",
        "inverse-surface": "#e4e2e2",
        "surface-container-lowest": "#0d0e0f",
        "on-primary-fixed-variant": "#474646",
        "tertiary-fixed-dim": "#e62200",
        "surface-variant": "#343535",
        "error-container": "#93000a",
        "on-secondary-container": "#b7b5b4",
        "on-error": "#690005",
        "background": "#121314",
        "on-secondary-fixed": "#1b1b1c",
        "tertiary-container": "#2e0804",
        "on-tertiary-fixed-variant": "#850e00",
        "inverse-on-surface": "#303031",
        "surface-dim": "#121314",
        "on-primary-container": "#7e7d7d",
        "on-background": "#e4e2e2",
        "on-surface": "#e4e2e2",
        "tertiary": "#ff2800",
        "primary-container": "#121212",
        "on-primary": "#313030",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-highest": "#343535",
        "inverse-primary": "#5f5e5e",
        "secondary": "#c8c6c5",
        "on-tertiary-container": "#ffaba3",
        "tertiary-fixed": "#ffc5be",
        "secondary-fixed": "#e5e2e1",
        "surface-container-high": "#292a2a",
        "surface-container": "#1f2020",
        "primary-fixed": "#e5e2e1",
        "on-secondary": "#303030",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1200px",
        "md": "24px",
        "gutter": "20px",
        "lg": "48px",
        "xl": "80px",
        "sm": "12px",
        "base": "8px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Archivo Narrow"],
        "display-lg": ["Archivo Narrow"],
        "headline-lg": ["Archivo Narrow"],
        "headline-md": ["Archivo Narrow"],
        "label-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
